version: '3.8'

services:
  db:
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: admin 
      POSTGRES_PASSWORD: 1234 
      POSTGRES_DB: supertokens
    ports:
      - 5432:5432
    networks:
      supertokens-networks:
        ipv4_address: 162.16.18.4
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'admin', '-d', 'supertokens']
      interval: 5s
      timeout: 5s
      retries: 5

  supertokens:
    image: registry.supertokens.io/supertokens/supertokens-postgresql:9.3.0
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 3567:3567
    environment:
      POSTGRESQL_CONNECTION_URI: "postgresql://admin:1234@db:5432/supertokens"
    restart: unless-stopped
    healthcheck:
      test: >
        bash -c 'exec 3<>/dev/tcp/127.0.0.1/3567 && echo -e "GET /hello HTTP/1.1\r\nhost: 127.0.0.1:3567\r\nConnection: close\r\n\r\n" >&3 && cat <&3 | grep "Hello"'
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      supertokens-networks:
        ipv4_address: 162.16.18.2
      
  
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    networks:
      supertokens-networks:
        ipv4_address: 162.16.18.3
      
networks:
  supertokens-networks:
    driver: bridge
    ipam:
      config:
        - subnet: 162.16.18.0/24
